name: KitaQueue_v2
options:
  bundleIdPrefix: com.kitaqueue
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_STRICT_CONCURRENCY: complete
  configs:
    Debug:
      CODE_SIGN_IDENTITY: "-"

targets:
  KitaQueue_v2:
    type: application
    platform: iOS
    sources:
      - path: KitaQueue_v2
        excludes:
          - "**/.DS_Store"
    resources:
      - path: KitaQueue_v2/Resources/Assets.xcassets
      - path: KitaQueue_v2/Resources/Gameplay.atlas
      - path: KitaQueue_v2/Resources/Shell.atlas
      - path: KitaQueue_v2/Resources/Sounds
      - path: KitaQueue_v2/Levels
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: KitaQueue_v2/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.kitaqueue.slidinggates
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
    info:
      path: KitaQueue_v2/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: true
        GADApplicationIdentifier: ca-app-pub-3940256099942544~1458002511
        NSUserTrackingUsageDescription: "This identifier will be used to deliver personalized ads to you."
        SKAdNetworkItems:
          - SKAdNetworkIdentifier: cstr6suwn9.skadnetwork

  KitaQueue_v2Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: KitaQueue_v2Tests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: KitaQueue_v2
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.kitaqueue.slidinggates.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/KitaQueue_v2.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/KitaQueue_v2"
        BUNDLE_LOADER: "$(TEST_HOST)"
